### PR TITLE
Feature/gt imports

### PR DESCRIPTION
**Pull request by arg0n1s**
-  Added the import feature, which allows the import of patterns or rules from other .gipsl or .gt files
-  Foreign imported patterns or rules can now be used as if they were defined within the current document
-  If patterns depend on other patterns transitively, they are imported as well
-  If required other metamodels are imported as well

### TODOS:
-  Automatically importing transitively required metamodels might lead to conflict with the imported metamodel of the current file. What to do if 2 unrelated metamodels are imported? How would an instance graph look like?
- Automatic import of transitively required patterns is pretty dumb at the moment. Basically everything from foreign files is imported indiscriminately. In the future only absolutely necessary patterns should be imported to avoid name conflicts
- What about static imports aka. name spaced imports?
- What about the deliberate import of all conents of foreign files?
- What about imports of foreign constraints, objectives, mappings etc.?

### CODE REVIEW

**Review by maxkratz — CHANGES_REQUESTED** [review]
Nice! The import functionality + suggestions work as expected. I've created some test cases for the import of GIPSL and GT files here: https://github.com/Echtzeitsysteme/gips-tests/pull/2. As far as I can see, everything behaves as expected and the tests are all green :).

*But* we should find another solution for the import path resolution:
Is there a current implementation for resolving relative paths in imports? (Maybe I just haven't seen it.)

For example, I used hard-coded absolute paths in my test implementation: https://github.com/Echtzeitsysteme/gips-tests/blob/5f2bc1b3d7f46bb9a62955c194fb20e68fccc354/gipsl.imports.sub/src/gipsl/Model.gipsl#L1-L5

The import of other GIPSL/GT files should be possible by using relative paths, otherwise the paths must be adapted if:
- One uses another OS than Windows (in this example)
- One uses another workspace/repo path or username
- One wants to implement a CI solution that uses GIPS(L) with imported files

Proposal: We could just use the "UNIX style"-based relative paths. In the test example, this would be
```
from "gipsl.imports.supera/src/gipsl/Model.gipsl" import mapGuestA
from "gipsl.imports.superb/src/gipsl/imports/superb/Rules.gt" import findMappedGuests
```

instead of

```
from "C:\Users\mkratz\git\gips-tests\gipsl.imports.supera\src\gipsl\Model.gipsl" import mapGuestA
from "C:\Users\mkratz\git\gips-tests\gipsl.imports.superb\src\gipsl\imports\superb\Rules.gt" import guestNotMapped
```

(Workspace-related or file-related would be fine for me!)

**Comment by arg0n1s** [comment]
### Added requested changes

1. Added support for project relative paths
2. Added import by package name for Gipsl models
3. Added mandatory package declaration for Gipsl models (must be unique workspace wide)

### TODO:

- generate packages and java classes based on the specified root package name
- namespace imported rules internally using their package names
- Automatically importing transitively required metamodels might lead to conflict with the imported metamodel of the current file. 
- What to do if 2 unrelated metamodels are imported? How would an instance graph look like?
- Automatic import of transitively required patterns is pretty dumb at the moment. Basically everything from foreign files is imported indiscriminately. In the future only absolutely necessary patterns should be imported to avoid name conflicts
- What about static imports aka. name spaced imports?
- What about the deliberate import of all conents of foreign files?
- What about imports of foreign constraints, objectives, mappings etc.?

**Review by maxkratz — APPROVED** [review]

**Comment by maxkratz** [comment]
One thing is still missing: The hello world example from the wizard must be updated. I'll have a look at it.

**Comment by maxkratz** [comment]
> One thing is still missing: The hello world example from the wizard must be updated. I'll have a look at it.

Fixed by https://github.com/Echtzeitsysteme/gips/pull/25/commits/3ef1559437c6eb45267ed3f79419223df90fe976.

**Pull request merged**
